import Alert from './alert.svg'
import Back from './back.svg'
import Call from './call.svg'
import Camera from './camera.svg'
import CheckboxUnChecked from './checkbox.svg'
import CheckboxChecked from './checkbox_checked.svg'
import Close from './close.svg'
import CloseWhite from './close_white.svg'
import CloseFilled from './close_fill.svg'
import Edit from './edit.svg'
import Key from './key.svg'
import Profile from './profile.svg'
import ArrowUp from './arrow_up.svg'
import ArrowDown from './arrow_down.svg'
import Schedule from './schedule.svg'
import AlertLarge from './alert_large.svg'
import SystemError from './system_error.svg'
import LoadError from './load_error.svg'
import NetworkError from './network_error.svg'
import LogoInspect from './logo_inspect.svg'
import LogoAssessment from './logo_assessment.svg'
import New from './new.svg'

export { Alert, ArrowUp, New, ArrowDown, Call, Camera, Key, LogoInspect, LogoAssessment, CheckboxUnChecked, CheckboxChecked, Close, CloseFilled, CloseWhite, Edit, Profile, Back, Schedule, AlertLarge, SystemError, LoadError, NetworkError }
